

DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS coffee_orders;
CREATE TABLE customers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(40) NOT NULL,
    phone INTEGER(10) UNIQUE,
    email VARCHAR(255) UNIQUE,
    points INTEGER DEFAULT 5 NOT NULL,
    created_at DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE coffee_orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    is_redeemed BOOLEAN DEFAULT "Not redeemed",
    ordered_at DEFAULT CURRENT_TIMESTAMP NOT NULL
);
